### ISSUE TITLE
Identity delete/inactivation and creation endpoints

### ISSUE THREAD

**Issue by mikron** [sflpro/identity#17]
Currently, there's an identity update endpoint available but one has to manually create an identity in the database to be able to update it through the API. Endpoints are required to make the management of the full identity lifecycle through the API possible.

The proposal is to make 2 endpoints:
* Identity creation endpoint at : PUT /identities/{identityId}
* Identity deletion endpoint at : DELETE /identities/{identityId}

**Comment by dnavre** [comment]
@mikron I updated the issue description to provide more details about it.

**Comment by dnavre** [comment]
Was resolved by PR #33
