### ISSUE TITLE
Failed attempts on authentication endpoint not working properly

### ISSUE THREAD

**Issue by mikron** [sflpro/identity#24]
When user fails to authenticate the credential failed attempts should be incremented. And when user successfully authenticated the failed attempts should be reset. 
Probably will need also block user from authentication based on some property.

**Comment by dnavre** [comment]
Added another issue for the blocking of authentication based on the number of authentication attempts https://github.com/sflpro/identity/issues/26 . The scope of this bug is only fixing the incrementing count of authentication failures in the identity entity.

**Comment by mikron** [comment]
Was resolved by PR #35
