### ISSUE TITLE
Authentication result of an identity should include a list of identity's permissions

### ISSUE THREAD

**Issue by dnavre** [sflpro/identity#28]
Currently, the result of a successful authentication includes the list of roles an identity has, this should be changed in favor of returning the list of permissions of an identity.
Checking access based on role assignment is a strongly discouraged practice, all access checks should be done based on the final permission list(produced after merging all permissions a user has been assigned to through roles).

**Comment by AniJan** [comment]
The issue is fixed.
Permissions set was added for authentication result of an identity.
